### ISSUE TITLE
Erro ao Clicar em Unfollow

### ISSUE THREAD

**Issue by elissonmichael** [devmode-community/twitter_clone_bootstrap#3]
Boa noite pessoal, 
Queria comentar que testei a aplicação agora pouco e queria ajudar reportando essa mensagem de erro.
![captura de tela de 2018-08-07 00-13-15](https://user-images.githubusercontent.com/1037192/43752266-bc3072be-99d6-11e8-9e91-ac18a12e0968.png)

**Comment by marcelobarreto** [comment]
Boa @elissonmichael , já consertei aqui, obrigado
